version: '3.9'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookingDatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./MySQL/data.sql:/docker-entrypoint-initdb.d/data.sql
      
  djangoapp:
    build:
      context: ./booking_system
    environment:
      - DJANGO_SETTINGS_MODULE=booking_system.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000